package com.ibm.etp.hibernate.pojo;

// Generated 2011-8-30 15:23:25 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Goodsinfo generated by hbm2java
 */
public class Goodsinfo implements java.io.Serializable {

	private Integer goodsno;
	private Goodstype goodstype;
	private String goodsname;
	private String goodsdesc;
	private Set<Ordergoods> ordergoodses = new HashSet<Ordergoods>(0);

	public Goodsinfo() {
	}

	public Goodsinfo(Integer goodsno) {
		this.goodsno = goodsno;
	}

	public Goodsinfo(Integer goodsno, Goodstype goodstype, String goodsname,
			String goodsdesc, Set<Ordergoods> ordergoodses) {
		this.goodsno = goodsno;
		this.goodstype = goodstype;
		this.goodsname = goodsname;
		this.goodsdesc = goodsdesc;
		this.ordergoodses = ordergoodses;
	}

	public Integer getGoodsno() {
		return this.goodsno;
	}

	public void setGoodsno(Integer goodsno) {
		this.goodsno = goodsno;
	}

	public Goodstype getGoodstype() {
		return this.goodstype;
	}

	public void setGoodstype(Goodstype goodstype) {
		this.goodstype = goodstype;
	}

	public String getGoodsname() {
		return this.goodsname;
	}

	public void setGoodsname(String goodsname) {
		this.goodsname = goodsname;
	}

	public String getGoodsdesc() {
		return this.goodsdesc;
	}

	public void setGoodsdesc(String goodsdesc) {
		this.goodsdesc = goodsdesc;
	}

	public Set<Ordergoods> getOrdergoodses() {
		return this.ordergoodses;
	}

	public void setOrdergoodses(Set<Ordergoods> ordergoodses) {
		this.ordergoodses = ordergoodses;
	}

}
