package com.ibm.etp.hibernate.pojo;

// Generated 2011-8-30 15:23:25 by Hibernate Tools 3.3.0.GA

/**
 * Ordergoods generated by hbm2java
 */
public class Ordergoods implements java.io.Serializable {

	private Integer ordergoodsno;
	private Orderinfo orderinfo;
	private Goodsinfo goodsinfo;
	private Integer price;
	private Integer amount;

	public Ordergoods() {
	}

	public Ordergoods(Integer ordergoodsno) {
		this.ordergoodsno = ordergoodsno;
	}

	public Ordergoods(Integer ordergoodsno, Orderinfo orderinfo,
			Goodsinfo goodsinfo, Integer price, Integer amount) {
		this.ordergoodsno = ordergoodsno;
		this.orderinfo = orderinfo;
		this.goodsinfo = goodsinfo;
		this.price = price;
		this.amount = amount;
	}

	public Integer getOrdergoodsno() {
		return this.ordergoodsno;
	}

	public void setOrdergoodsno(Integer ordergoodsno) {
		this.ordergoodsno = ordergoodsno;
	}

	public Orderinfo getOrderinfo() {
		return this.orderinfo;
	}

	public void setOrderinfo(Orderinfo orderinfo) {
		this.orderinfo = orderinfo;
	}

	public Goodsinfo getGoodsinfo() {
		return this.goodsinfo;
	}

	public void setGoodsinfo(Goodsinfo goodsinfo) {
		this.goodsinfo = goodsinfo;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

}
