package com.ibm.etp.common.hibernate.pojo;

// Generated 2011-8-29 9:29:24 by Hibernate Tools 3.3.0.GA

/**
 * Bonus generated by hbm2java
 */
public class Bonus implements java.io.Serializable {

	private BonusId id;

	public Bonus() {
	}

	public Bonus(BonusId id) {
		this.id = id;
	}

	public BonusId getId() {
		return this.id;
	}

	public void setId(BonusId id) {
		this.id = id;
	}

}
