package com.ibm.etp.common.hibernate.pojo;

// Generated 2011-8-29 9:29:24 by Hibernate Tools 3.3.0.GA

/**
 * SalgradeId generated by hbm2java
 */
public class SalgradeId implements java.io.Serializable {

	private Double grade;
	private Double losal;
	private Double hisal;

	public SalgradeId() {
	}

	public SalgradeId(Double grade, Double losal, Double hisal) {
		this.grade = grade;
		this.losal = losal;
		this.hisal = hisal;
	}

	public Double getGrade() {
		return this.grade;
	}

	public void setGrade(Double grade) {
		this.grade = grade;
	}

	public Double getLosal() {
		return this.losal;
	}

	public void setLosal(Double losal) {
		this.losal = losal;
	}

	public Double getHisal() {
		return this.hisal;
	}

	public void setHisal(Double hisal) {
		this.hisal = hisal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SalgradeId))
			return false;
		SalgradeId castOther = (SalgradeId) other;

		return ((this.getGrade() == castOther.getGrade()) || (this.getGrade() != null
				&& castOther.getGrade() != null && this.getGrade().equals(
				castOther.getGrade())))
				&& ((this.getLosal() == castOther.getLosal()) || (this
						.getLosal() != null
						&& castOther.getLosal() != null && this.getLosal()
						.equals(castOther.getLosal())))
				&& ((this.getHisal() == castOther.getHisal()) || (this
						.getHisal() != null
						&& castOther.getHisal() != null && this.getHisal()
						.equals(castOther.getHisal())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGrade() == null ? 0 : this.getGrade().hashCode());
		result = 37 * result
				+ (getLosal() == null ? 0 : this.getLosal().hashCode());
		result = 37 * result
				+ (getHisal() == null ? 0 : this.getHisal().hashCode());
		return result;
	}

}
