package com.ibm.etp.common.hibernate.pojo;

// Generated 2011-8-29 9:29:24 by Hibernate Tools 3.3.0.GA

/**
 * Salgrade generated by hbm2java
 */
public class Salgrade implements java.io.Serializable {

	private SalgradeId id;

	public Salgrade() {
	}

	public Salgrade(SalgradeId id) {
		this.id = id;
	}

	public SalgradeId getId() {
		return this.id;
	}

	public void setId(SalgradeId id) {
		this.id = id;
	}

}
