package com.ibm.etp.hibernate.pojo;

// Generated 2011-8-29 10:59:14 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Goodstype generated by hbm2java
 */
public class Goodstype implements java.io.Serializable {

	private Integer goodstypeno;
	private String goodstypename;
	private Set<Goodsinfo> goodsinfos = new HashSet<Goodsinfo>(0);

	public Goodstype() {
	}

	public Goodstype(Integer goodstypeno) {
		this.goodstypeno = goodstypeno;
	}

	public Goodstype(Integer goodstypeno, String goodstypename,
			Set<Goodsinfo> goodsinfos) {
		this.goodstypeno = goodstypeno;
		this.goodstypename = goodstypename;
		this.goodsinfos = goodsinfos;
	}

	public Integer getGoodstypeno() {
		return this.goodstypeno;
	}

	public void setGoodstypeno(Integer goodstypeno) {
		this.goodstypeno = goodstypeno;
	}

	public String getGoodstypename() {
		return this.goodstypename;
	}

	public void setGoodstypename(String goodstypename) {
		this.goodstypename = goodstypename;
	}

	public Set<Goodsinfo> getGoodsinfos() {
		return this.goodsinfos;
	}

	public void setGoodsinfos(Set<Goodsinfo> goodsinfos) {
		this.goodsinfos = goodsinfos;
	}

}
