package com.ibm.etp.hibernate.pojo;

// Generated 2011-8-29 10:59:14 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orderinfo generated by hbm2java
 */
public class Orderinfo implements java.io.Serializable {

	private Integer orderno;
	private Ordertype ordertype;
	private Userinfo userinfo;
	private Date orderdate;
	private Set<Ordergoods> ordergoodses = new HashSet<Ordergoods>(0);

	public Orderinfo() {
	}

	public Orderinfo(Integer orderno) {
		this.orderno = orderno;
	}

	public Orderinfo(Integer orderno, Ordertype ordertype, Userinfo userinfo,
			Date orderdate, Set<Ordergoods> ordergoodses) {
		this.orderno = orderno;
		this.ordertype = ordertype;
		this.userinfo = userinfo;
		this.orderdate = orderdate;
		this.ordergoodses = ordergoodses;
	}

	public Integer getOrderno() {
		return this.orderno;
	}

	public void setOrderno(Integer orderno) {
		this.orderno = orderno;
	}

	public Ordertype getOrdertype() {
		return this.ordertype;
	}

	public void setOrdertype(Ordertype ordertype) {
		this.ordertype = ordertype;
	}

	public Userinfo getUserinfo() {
		return this.userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	public Date getOrderdate() {
		return this.orderdate;
	}

	public void setOrderdate(Date orderdate) {
		this.orderdate = orderdate;
	}

	public Set<Ordergoods> getOrdergoodses() {
		return this.ordergoodses;
	}

	public void setOrdergoodses(Set<Ordergoods> ordergoodses) {
		this.ordergoodses = ordergoodses;
	}

}
