/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.webshopping.struts.action;

import java.util.LinkedHashSet;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.validator.DynaValidatorForm;
import org.webshopping.struts.action.bean.Trolley;

/**
 * MyEclipse Struts Creation date: 04-20-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/show/buy/trolley" name="buyForm"
 *                input="/show/buy/trolley.jsp" scope="request" validate="true"
 */
public class BuyAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@SuppressWarnings("unchecked")
	public ActionForward append(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		DynaValidatorForm buyForm = (DynaValidatorForm) form;
		HttpSession session = request.getSession();

		Trolley trolleyBean = new Trolley();
		trolleyBean.setPid(buyForm.getString("pid"));
		trolleyBean.setName(buyForm.getString("name"));
		trolleyBean.setUnitprice(buyForm.getString("unitprice"));

		Set<Trolley> trolleys = (Set<Trolley>) session.getAttribute("trolley");
		if (trolleys == null) {
			trolleys = new LinkedHashSet<Trolley>();
			session.setAttribute("trolley", trolleys);
		}
		trolleys.add(trolleyBean);
		return mapping.findForward("success");
	}

	@SuppressWarnings("unchecked")
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		DynaValidatorForm buyForm = (DynaValidatorForm) form;
		HttpSession session = request.getSession();

		Set<Trolley> trolleys = (Set<Trolley>) session.getAttribute("trolley");
		if (trolleys != null && buyForm.get("pid") != null) {
			for (Trolley t : trolleys) {
				if (buyForm.get("pid").equals(t.getPid())) {
					trolleys.remove(t);
					if(trolleys.isEmpty()){
						session.removeAttribute("trolley");
					}
					break;
				}
			}
		}

		return mapping.findForward("success");
	}
}