/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.webshopping.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.apache.struts.validator.DynaValidatorForm;

/**
 * MyEclipse Struts Creation date: 04-02-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/login" name="loginForm" input="/login.jsp"
 *                scope="request" validate="true"
 * @struts.action-forward name="success" path="/index" redirect="true"
 */
public class LoginAction extends UserBaseAction {
	/*
	 * Generated Methods
	 */

	/**
	 * 用户登录
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		DynaValidatorForm loginForm = (DynaValidatorForm) form;
		String username = loginForm.getString("username");
		boolean success = this.iuserService.login(username, loginForm
				.getString("password"));
		if (success) {
			request.getSession().setAttribute("username", username);
			return mapping.findForward("lastPage");
		} else {
			/* 登录失败,用户名密码不正确 */
			ActionMessages error = new ActionMessages();
			error.add("loginerr", new ActionMessage("loginForm.err"));
			this.addErrors(request, error);
			return mapping.getInputForward();
		}
	}
}