/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.webshopping.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.validator.DynaValidatorForm;
import org.webshopping.bean.Product;
import org.webshopping.service.IProductService;

/**
 * MyEclipse Struts Creation date: 04-10-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/product" name="productForm" input="/error.jsp"
 *                parameter="method" scope="request" validate="true"
 * @struts.action-forward name="success" path="/index.jsp"
 */
public class ProductAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private IProductService iproductService;

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward listNew(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {

		/* 查询最新的几个产品，默认5个 */
		List<Product> newProduct = iproductService
				.getNewProducts(IProductService.MAX_ROW);
		request.setAttribute("newProduct", newProduct);
		return mapping.findForward("successNew");
	}

	public ActionForward products(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		DynaValidatorForm productForm = (DynaValidatorForm) form;
		int cid = Integer.parseInt((String) productForm.get("cid"));
		int maxRow = IProductService.MAX_ROW;
		int currentPage = IProductService.CURRENT_PAGE;
		/* 按商品分类查询相应的商品 */
		List<Product> products = iproductService.getProducts(cid, maxRow,
				currentPage);
		request.setAttribute("products", products);
		return mapping.findForward("successProducts");
	}

	public ActionForward showOne(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		DynaValidatorForm productForm = (DynaValidatorForm) form;
		int pid = Integer.parseInt((String) productForm.get("pid"));

		Product product = iproductService.getProduct(pid);

		productForm.set("name", product.getName());
		productForm.set("unitprice", product.getUnitprice().toString());
		productForm.set("discount", product.getDiscount().toString());
		productForm.set("picture", product.getPicture());
		productForm.set("descr", product.getDescr());
		request.setAttribute("showOne", "true");
		return mapping.findForward("successShowOne");
	}

	public void setIproductService(IProductService iproductService) {
		this.iproductService = iproductService;
	}
}