/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.webshopping.struts.action;

import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.validator.DynaValidatorForm;
import org.webshopping.bean.Orderitem;
import org.webshopping.bean.Salesorder;
import org.webshopping.service.ISalesrderService;
import org.webshopping.struts.action.bean.Trolley;

/**
 * MyEclipse Struts Creation date: 04-29-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/show/buy/saleSorder" name="saleSorderForm"
 *                input="/error.jsp" parameter="method" scope="request"
 *                validate="true"
 */
public class SaleSorderAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	private ISalesrderService isalesrderService;

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@SuppressWarnings("unchecked")
	public ActionForward purchase(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaValidatorForm saleSorderForm = (DynaValidatorForm) form;
		HttpSession session = request.getSession();
		String username = (String) session.getAttribute("username");

		Salesorder salesOrder = new Salesorder();
		salesOrder.setAddress(saleSorderForm.getString("address"));
		salesOrder.setPhone(saleSorderForm.getString("phone"));

		Set<Orderitem> orderItems = new LinkedHashSet<Orderitem>();

		String[] countStr = saleSorderForm.getStrings("count");
		Set<Trolley> trolleys = (Set<Trolley>) session.getAttribute("trolley");
		int i = 0;
		for (Trolley t : trolleys) {
			Orderitem o = new Orderitem();
			o.setCount(Integer.parseInt(countStr[i]));
			o.setUnitprice(Float.parseFloat(t.getUnitprice()));
			o.setName(t.getName());
			o.setPid(Integer.parseInt(t.getPid()));
			o.setSalesorder(salesOrder);
			orderItems.add(o);

			++i;
		}

		this.isalesrderService.createSalesorder(username, salesOrder,
				orderItems);
		session.removeAttribute("trolley");
		
		return mapping.findForward("success");
	}

	public ActionForward show(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String username = (String) request.getSession().getAttribute("username");
		List<Salesorder> salesOrders = this.isalesrderService.getAll(username);
		request.setAttribute("salesOrders", salesOrders);
		return mapping.findForward("successShow");
	}

	public void setIsalesrderService(ISalesrderService isalesrderService) {
		this.isalesrderService = isalesrderService;
	}
}