package com.ibm.etp.hibernate.pojo;

// Generated 2011-8-26 10:15:11 by Hibernate Tools 3.3.0.GA

/**
 * TSeq generated by hbm2java
 */
public class TSeq implements java.io.Serializable {

	private Long id;
	private String name;
	private String aaa;

	public TSeq() {
	}

	public TSeq(Long id) {
		this.id = id;
	}

	public TSeq(Long id, String name, String aaa) {
		this.id = id;
		this.name = name;
		this.aaa = aaa;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAaa() {
		return this.aaa;
	}

	public void setAaa(String aaa) {
		this.aaa = aaa;
	}

}
